src/Entity/Tournoi.php
<?php

namespace App\Entity;

use App\Repository\TournoiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TournoiRepository::class)
 */
class Tournoi
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\ManyToMany(targetEntity=Arbitre::class, inversedBy="tournois")
     */
    private $arbitres;

    /**
     * @ORM\OneToMany(targetEntity=Rencontre::class, mappedBy="tournoi")
     */
    private $rencontres;

    /**
     * @ORM\OneToMany(targetEntity=Journee::class, mappedBy="tournoi")
     */
    private $journees;

    /**
     * @ORM\ManyToMany(targetEntity=Ramasseur::class, inversedBy="tournois")
     */
    private $ramasseurs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_tour;

    /**
     * @ORM\ManyToMany(targetEntity=Equipe::class, inversedBy="tournois")
     */
    private $equipes;

    public function __construct()
    {
        $this->arbitres = new ArrayCollection();
        $this->rencontres = new ArrayCollection();
        $this->journees = new ArrayCollection();
        $this->ramasseurs = new ArrayCollection();
        $this->equipes = new ArrayCollection();
    }

    public function __toString()
    {
        return 'Tournoi '.$this->type. ' - '. $this->date_debut->format('m-Y');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }


    /**
     * @return Collection|Arbitre[]
     */
    public function getArbitres(): Collection
    {
        return $this->arbitres;
    }

    public function addArbitre(Arbitre $arbitre): self
    {
        if (!$this->arbitres->contains($arbitre)) {
            $this->arbitres[] = $arbitre;
        }

        return $this;
    }

    public function removeArbitre(Arbitre $arbitre): self
    {
        $this->arbitres->removeElement($arbitre);

        return $this;
    }

    /**
     * @return Collection|Rencontre[]
     */
    public function getRencontres(): Collection
    {
        return $this->rencontres;
    }

    public function addRencontre(Rencontre $rencontre): self
    {
        if (!$this->rencontres->contains($rencontre)) {
            $this->rencontres[] = $rencontre;
            $rencontre->setTournoi($this);
        }

        return $this;
    }

    public function removeRencontre(Rencontre $rencontre): self
    {
        if ($this->rencontres->removeElement($rencontre)) {
            // set the owning side to null (unless already changed)
            if ($rencontre->getTournoi() === $this) {
                $rencontre->setTournoi(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Journee[]
     */
    public function getJournees(): Collection
    {
        return $this->journees;
    }

    public function addJournee(Journee $journee): self
    {
        if (!$this->journees->contains($journee)) {
            $this->journees[] = $journee;
            $journee->setTournoi($this);
        }

        return $this;
    }

    public function removeJournee(Journee $journee): self
    {
        if ($this->journees->removeElement($journee)) {
            // set the owning side to null (unless already changed)
            if ($journee->getTournoi() === $this) {
                $journee->setTournoi(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ramasseur[]
     */
    public function getRamasseurs(): Collection
    {
        return $this->ramasseurs;
    }

    public function addRamasseur(Ramasseur $ramasseur): self
    {
        if (!$this->ramasseurs->contains($ramasseur)) {
            $this->ramasseurs[] = $ramasseur;
        }

        return $this;
    }

    public function removeRamasseur(Ramasseur $ramasseur): self
    {
        $this->ramasseurs->removeElement($ramasseur);

        return $this;
    }

    public function getNombreTour(): ?int
    {
        return $this->nombre_tour;
    }

    public function setNombreTour(int $nombre_tour): self
    {
        $this->nombre_tour = $nombre_tour;

        return $this;
    }

    /**
     * @return Collection|Equipe[]
     */
    public function getEquipes(): Collection
    {
        return $this->equipes;
    }

    public function addEquipe(Equipe $equipe): self
    {
        if (!$this->equipes->contains($equipe)) {
            $this->equipes[] = $equipe;
        }

        return $this;
    }

    public function removeEquipe(Equipe $equipe): self
    {
        $this->equipes->removeElement($equipe);

        return $this;
    }
}

src/Controller/PlanningController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\RencontreRepository;
use App\Repository\TournoiRepository;
use App\Repository\JourneeRepository;
use App\Entity\Tournoi;
use App\Entity\Journee;

class PlanningController extends AbstractController
{
   /**
     * @Route("/planning/affichage_tournois", name="planning_tournoi")
     */
    public function planning(TournoiRepository $TournoiRepository): Response
    {
        return $this->render('planning/index.html.twig', [
            'controller_name' => 'PlanningController',
            'tournois' => $TournoiRepository -> findAll(),

        ]);
    }

    /**
     * @Route("/planning/{tournoi}/affichage_journee", name="planning_journee")
     */
    public function planning_journee(Tournoi $tournoi, JourneeRepository $journeeRepository): Response
    {
        return $this->render('planning/journee.html.twig', [
            'controller_name' => 'PlanningController',
            'tournoi' => $tournoi,
            'journees' => $journeeRepository -> findByTournoi($tournoi),
        ]);
    }
     /**
     * @Route("/planning/{journee}/affichage_rencontre", name="planning_rencontre")
     */
     public function planning_rencontre( Journee $journee, RencontreRepository $rencontreRepository): Response
    {
        return $this->render('planning/rencontre.html.twig', [
            'controller_name' => 'PlanningController',
            'journees' => $journee,
            'rencontres' => $rencontreRepository -> findByJournee($journee),
        ]);
    }
}

templates/planning/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Hello PlanningController!
                        
                    
                
            
        
    
{% endblock %}

{% block body %}
    <div data-aos="fade" class="container mainplanning text-center">
        <div class="container_recherche">
            <h1>
                Planning des matchs - Affichage des différents Tournois
            </h1>
        </div>
        <div class="container_affichage_tournois">
            {% for tournoi in tournois %}
                <a class="tournois" href="{{ path('planning_journee',{'tournoi': tournoi.id}) }}">
                    <div class="lieux">
                        <p>
                            <i class="icone-l fas fa-map-marker-alt"></i>
                            Tournoi 
                            {{ tournoi.type }}
                        </p>

                        <p>
                            <i class="icone-l far fa-clock"></i>
                            Debut 
                            {{ tournoi.datedebut|date("m/d/Y") }}
                        </p>

                    </div>
                    <div class="choix">
                        <p>
                            Choisir 
                            <i class="icone-r fas fa-arrow-right"></i>
                        </p>
                    </div>

                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/planning/journee.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PlanningController!
{% endblock %}

{% block body %}
	<div data-aos="fade" class="container mainbilleterie text-center">
		<div class="container_recherche">
			<h1>Journées du tournoi
				{{tournoi.type}}
				du
				{{ tournoi.dateDebut|date('d/m/Y') }}
			</h1>
		</div>
		<div class="container_journee">
			{% for journee in journees %}
				<a href="" class="container_journee_infos">
					<div class="infos">
						<h2>{{ journee }}</h2>
					</div>
					<div class="versus" id="item_match_result">
						{% for rencontre in journee.rencontres %}
							<div class="regroup-tab">
								<p class="court">Court :
									{{rencontre.court}}</p>
								<div class="tableau">
									<p class="name equipe1">{{ rencontre.equipes[0] }}</p>
									<p class="vs">vs</p>
									<p class="name equipe2">{{ rencontre.equipes[1] }}</p>
								</div>
								<div>
									{% for t in 0..(rencontre.score|length / 2)  %}
										<span class="text score">{{ rencontre.score|slice(t*2, 1) }}</span>
									{% endfor %}
								</div>
								<div class="line_separator"></div>
								<div>
									{% for t in 0..(rencontre.score|length / 2)  %}
										<span class="text score">{{ rencontre.score|slice(t*2+1, 1) }}</span>
									{% endfor %}
								</div>
							</div>
						{% endfor %}
					</div>
				</a>
			{% endfor %}

		</div>

	</div>
{% endblock %}

templates/planning/rencontre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PlanningController!{% endblock %}

{% block body %}
<div class="container">
{% for rencontre in rencontres %}
			 {{rencontre.equipes[0]}}
              {{rencontre.equipes[1]}}
			{% endfor %}
</div>
{% endblock %}